### ISSUE TITLE
REQUEST:

### ISSUE THREAD

**Issue by PascalGitz** [Dlubal-Software/RFEM_Python_Client#226]
Hello Dlubal-Team

I'm looking to add a nodal support via python. Is it possible to define the stiffness with a diagram, as it can be done by "hand" (shown in the first image) ?

![image](https://user-images.githubusercontent.com/115550508/221814941-e1524ced-2582-420c-aa6a-3693f6fecdec.png)

As documented in the manual i can add constant values with the "support" parameter. But I could not figure it out how to add it with a diagram.

![image](https://user-images.githubusercontent.com/115550508/221815098-1fc2b298-95e2-4258-9466-9a848e033b08.png)

Could you guide me how to do this properly

Best regards,

Pascal

**Comment by OndraMichal** [comment]
Hi @PascalGitz,
thank you for the question. You can set every parameter by setting **params** (type dictionary, optional) parameter. Because it is set as the end of the routine, it can override any previous parameters. 
How to use it:
First printout object of your interest in the command-line. To do it the code would look like this:
```
from suds.client import Client

client = Client('http://localhost:8081/wsdl')
new = client.service.get_active_model()+'wsdl'
model = Client(new)

print(model.service.get_nodal_support(1))
```
You will get full description of Nodal Support no.1. From this you can figure out the structure of the object and create whole new object with parameters you intend. For example, if you want to descibe support condition in X direction via diagram, focus on these parameters:
```
diagram_along_x_end = "DIAGRAM_ENDING_TYPE_CONTINUOUS"
diagram_along_x_is_sorted = True
diagram_along_x_start = "DIAGRAM_ENDING_TYPE_CONTINUOUS"
diagram_along_x_symmetric = True
diagram_along_x_table =
    (array_of_nodal_support_diagram_along_x_table){
        nodal_support_diagram_along_x_table[] =
            (nodal_support_diagram_along_x_table_row){
                no = 1
                description = None
                row =
                    (nodal_support_diagram_along_x_table){
                       displacement = -0.0001
                       force = -200000000.0
                       spring = 3900000000000.0
                       note = None
                   }
              },
             (nodal_support_diagram_along_x_table_row){
                no = 2
                description = None
                row =
                    (nodal_support_diagram_along_x_table){
                        displacement = -5e-05
                        force = -5000000.0
                        spring = 100000000000.0
                        note = None
                   }
             },
       }
```
You can then write:
```
NodalSupport(..., params = {'diagram_along_x_end':"DIAGRAM_ENDING_TYPE_CONTINUOUS"})
```
To define something like **diagram_along_x_table** you can set it like this:
```
diagram_along_x= model.clientModel.factory.create('ns0:response_spectrum.user_defined_response_spectrum')
for i,j in enumerate(nodal_support_diagrams):
    ns = model.clientModel.factory.create('ns0:nodal_support_diagram_along_x_table_row')
    ns.no = i+1
    ns.row.displacement= user_defined_spectrum[i][0]
    rsp.row.force= user_defined_spectrum[i][1]
    ns.row.force= user_defined_spectrum[i][2]

    diagram_along_x.nodal_support_diagram_along_x_table.append(ns)

NodalSupport(..., params = {'diagram_along_x_table' : diagram_along_x})
```
This is the process we use to develop this library.
