### ISSUE TITLE
Structure of 'ns0:calculate_specific_loadings' 

### ISSUE THREAD

**Issue by BjornSchweder** [Dlubal-Software/RFEM_Python_Client#233]
Can't quite wrap my head around how the first argument of 

      Model.clientModel.service.calculate_specific(ns0:calculate_specific_loadings loadings, xs:boolean skip_warnings)

is structured. 

With

     test = Model.clientModel.factory.create('ns0:calculate_specific_loadings')
     test.loading = [1,3]
     Model.clientModel.service.calculate_specific(test.loading,True)

I get  "Server raised fault: 'Given data do not have expected structure.'"

Since the code I'm working with is for editing an already created client model, I tried

    lc1 = Model.clientModel.service.get_load_case(1) 
    test = Model.clientModel.factory.create('ns0:calculate_specific_loadings')
    test.loading = [lc1]
    Model.clientModel.service.calculate_specific(test.loading,True)
Which returns error: **Server raised fault: 'loadings: '**

But it's more or less shooting in the dark, need some help with this one. 

There is a function, 

     CalculateSelectedCases()

But that tries to create

      'ns0:array_of_calculate_specific_objects_elements'

which gives error: **Type not found: 'ns0:array_of_calculate_specific_objects_elements'**
This type doesn't seem to exist anywhere in the documentation, atleast that i can find.

**Comment by OndraMichal** [comment]
Hi @BjornSchweder,
I have researched this issue and am getting the same results. I'll look into it again today and give you a solution if I find it.

**Comment by jarabroz** [comment]
Hi @BjornSchweder ,
I have recently made some changes in CalculateSpecific due to the bug you pointed out. You need to create an array which contains what you want to calculate.  You need to define the type of object and its no. See here
`
specificObjectsToCalculate = model.clientModel.factory.create('ns0:calculate_specific_loadings')
specificObjectsToCalculateLS = model.clientModel.factory.create('ns0:calculate_specific_loadings.loading')            specificObjectsToCalculateLS.no = 1
specificObjectsToCalculateLS.type = ObjectTypes.E_OBJECT_TYPE_LOAD_CASE.name
specificObjectsToCalculate.loading.append(specificObjectsToCalculateLS)
calculationMessages = model.clientModel.service.calculate_specific(specificObjectsToCalculate,skipWarnings)
`
