### ISSUE TITLE
REQUEST: Async / batch requests

### ISSUE THREAD

**Issue by gvandewiel86** [Dlubal-Software/RFEM_Python_Client#251]
**Is your feature request related to a problem? Please describe.**
As far as we are aware there is no access to the tools within RFEM to manipulate the geometry of the model (for instance move / rotate commands). We are planning to work on a rather large model (which we can't share due to a signed NDA) which we need to rotate multiple times. The number of nodes currently involved is ~1500 which with the current setup are to be relocated one by one using a single SOAP request for each node. Currently a single rotation of all these nodes takes approximately 10-15 seconds. 

**Describe the solution you'd like**
Either the option to dump the whole set of new coordinates in one request (i.e. in a single batch) or have access to the manipulation tools in RFEM. Alternatively asynchronous SOAP requests might be an option as well depending on the capabilities of the SOAP server and the suds library (Zeep could be an alternative SOAP library which does support asyncio).

**Describe alternatives you've considered**

**Additional context**

**Comment by OndraMichal** [comment]
Hi @gvandewiel86,
we are aware that these tools would make life easier. We have selection functions that are necessary so manipulation tools could hopefully be implemented sooner rather than later.

Unfortunately, SUDS or SOAP do not support packing multiple statements into a batch. I researched this topic some time ago. Asynchronous calls won't help either, since sequential calls are a must for this type of operation. A line cannot be created before the nodes are created. And unfortunately, ZEEP was also investigated, but it does not support our way of using the client. Trust me, we've tried it at least twice that I know of.
