### ISSUE TITLE
BUG: Structure Modification not yet assignable to loadcombination or resultcombination

### ISSUE THREAD

**Issue by JesperWB** [Dlubal-Software/RFEM_Python_Client#312]
**Describe the bug**
When setting up a structure modification it seems like there is no option available to assign it to a specific load combination or result combination. I would like to use a lowerbound and upperbound multiplication factor on the surface support stiffness. This will have to be assigned to a specific loadcombination and later combined in an envelope using a result combination. This used to be available in RFEM5.

**To Reproduce**
1. create concrete plate, supported by a support surface with a certain spring stiffness.
2. create loadcase, unit surface load, assign loadcase to 2 loadcombinations (1 for upperbound & 1 for lowerbound stiffness).
3. Assign both loadcombinations to a resultclass.
4. try to setup a structure modification of the support surface assigned to 1 of the loadcombinations --> seems not possible

**Expected behavior**
an option to assign the structure modification to a loadcombination or resultclass

**Comment by bjoernsteinhagen** [comment]
Hi @JesperWB , I am going to jump in on this issue since I have just dealt with it myself and found a work-around. 

I presume, that in the load combination function call, you have the `structure_modification` flag set to `True`? Then, use the "params" parameter to assign the modification to the respective combination using the dictionary keyword "structure_modification" . 

Below is an example to assign a structure modification with the number "3" to the LoadCombination "1".
`LoadCombination(1, ..., structure_modification = True, params = {"structure_modification : 3"}`
